import { BookDTO } from '../src/types/BookDTO'

export const books: BookDTO[] = [
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    price: 14.99,
  },
  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    price: 24.99,
  },
  { title: '1984', author: 'George Orwell', genre: 'Dystopian', price: 12.99 },
  {
    title: 'Animal Farm',
    author: 'George Orwell',
    genre: 'Political Satire',
    price: 9.99,
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    genre: 'Sci-Fi',
    price: 13.49,
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    genre: 'Sci-Fi',
    price: 11.99,
  },
  { title: 'Dune', author: 'Frank Herbert', genre: 'Sci-Fi', price: 16.99 },
  {
    title: 'Foundation',
    author: 'Isaac Asimov',
    genre: 'Sci-Fi',
    price: 15.99,
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Classic',
    price: 10.99,
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Classic',
    price: 11.99,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Classic',
    price: 10.49,
  },
  {
    title: 'Moby Dick',
    author: 'Herman Melville',
    genre: 'Classic',
    price: 13.99,
  },
  {
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    genre: 'Classic',
    price: 14.49,
  },
  {
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    genre: 'Classic',
    price: 15.99,
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Romance',
    price: 9.99,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    genre: 'Romance',
    price: 11.49,
  },
  {
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    genre: 'Romance',
    price: 10.99,
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    genre: 'Fiction',
    price: 12.49,
  },
  {
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    genre: 'Fiction',
    price: 8.99,
  },
  {
    title: 'Harry Potter and the Sorcerer’s Stone',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    price: 14.49,
  },
  {
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    price: 14.49,
  },
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    price: 15.99,
  },
  {
    title: 'The Wise Man’s Fear',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    price: 17.99,
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    genre: 'Post-Apocalyptic',
    price: 12.99,
  },
  {
    title: 'The Handmaid’s Tale',
    author: 'Margaret Atwood',
    genre: 'Dystopian',
    price: 13.99,
  },
  {
    title: 'Slaughterhouse-Five',
    author: 'Kurt Vonnegut',
    genre: 'Sci-Fi',
    price: 11.99,
  },
  {
    title: 'The Shining',
    author: 'Stephen King',
    genre: 'Horror',
    price: 14.99,
  },
  { title: 'It', author: 'Stephen King', genre: 'Horror', price: 18.99 },
  { title: 'Dracula', author: 'Bram Stoker', genre: 'Horror', price: 10.99 },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    genre: 'Horror',
    price: 9.99,
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    genre: 'Crime',
    price: 14.99,
  },
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    genre: 'Thriller',
    price: 13.99,
  },
  {
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    genre: 'Thriller',
    price: 12.99,
  },
  {
    title: 'The Hitchhiker’s Guide to the Galaxy',
    author: 'Douglas Adams',
    genre: 'Sci-Fi',
    price: 11.49,
  },
  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    genre: 'Non-fiction',
    price: 19.99,
  },
  {
    title: 'Homo Deus',
    author: 'Yuval Noah Harari',
    genre: 'Non-fiction',
    price: 18.99,
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    genre: 'Non-fiction',
    price: 18.49,
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    genre: 'Non-fiction',
    price: 17.99,
  },
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    genre: 'Programming',
    price: 29.99,
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt',
    genre: 'Programming',
    price: 27.99,
  },
  {
    title: 'Design Patterns',
    author: 'Erich Gamma',
    genre: 'Programming',
    price: 34.99,
  },
  {
    title: 'Refactoring',
    author: 'Martin Fowler',
    genre: 'Programming',
    price: 31.99,
  },
  {
    title: 'You Don’t Know JS',
    author: 'Kyle Simpson',
    genre: 'Programming',
    price: 24.99,
  },
  {
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    genre: 'Programming',
    price: 23.99,
  },
  {
    title: 'The Clean Coder',
    author: 'Robert C. Martin',
    genre: 'Programming',
    price: 26.99,
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    genre: 'Psychology',
    price: 16.99,
  },
  {
    title: 'The Art of War',
    author: 'Sun Tzu',
    genre: 'Philosophy',
    price: 8.99,
  },
]
